"""new

Revision ID: 0646f6ba7dd9
Revises: e2412789c190
Create Date: 2024-04-28 18:27:43.198549

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0646f6ba7dd9'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('warehouse_price', sa.Float(), nullable=False))
    op.add_column('item', sa.Column('retail_price', sa.Float(), nullable=False))
    op.add_column('item', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.drop_column('item', 'title')
    op.drop_column('item', 'owner_id')
    op.drop_column('item', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('item_owner_id_fkey', 'item', 'user', ['owner_id'], ['id'])
    op.drop_column('item', 'name')
    op.drop_column('item', 'retail_price')
    op.drop_column('item', 'warehouse_price')
    # ### end Alembic commands ###
