"""new3

Revision ID: 173fb719bc09
Revises: 0646f6ba7dd9
Create Date: 2024-04-28 18:50:52.665182

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '173fb719bc09'
down_revision = '0646f6ba7dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('item', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('item', 'warehouse_price')
    op.drop_column('item', 'retail_price')
    op.drop_column('item', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('retail_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('warehouse_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('item', 'title')
    op.drop_column('item', 'description')
    # ### end Alembic commands ###
