"""update store items by id relationship entities

Revision ID: 34e7375bed32
Revises: 4325ee361164
Create Date: 2024-04-29 18:13:15.213903

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '34e7375bed32'
down_revision = '4325ee361164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
