"""update store items by id entities

Revision ID: 4325ee361164
Revises: b2ef16f56d09
Create Date: 2024-04-29 18:09:42.136260

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4325ee361164'
down_revision = 'b2ef16f56d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
