"""update purchase entity new

Revision ID: 4414aa49aa48
Revises: c01da1e1fb54
Create Date: 2024-04-29 22:52:18.195210

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4414aa49aa48'
down_revision = 'c01da1e1fb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
