"""updated models with proper PKs

Revision ID: 569385261b89
Revises: 570653d30e62
Create Date: 2024-04-29 13:31:49.502805

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '569385261b89'
down_revision = '570653d30e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
