"""new4

Revision ID: 71e71ac5005d
Revises: 173fb719bc09
Create Date: 2024-04-28 18:52:38.062247

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '71e71ac5005d'
down_revision = '173fb719bc09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('warehouse_price', sa.Float(), nullable=False))
    op.add_column('item', sa.Column('retail_price', sa.Float(), nullable=False))
    op.add_column('item', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('item', 'title')
    op.drop_column('item', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('item', 'name')
    op.drop_column('item', 'retail_price')
    op.drop_column('item', 'warehouse_price')
    # ### end Alembic commands ###
