"""update purchase entity

Revision ID: c01da1e1fb54
Revises: 57149936812e
Create Date: 2024-04-29 22:48:34.199792

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c01da1e1fb54'
down_revision = '57149936812e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
