"""revert

Revision ID: e46c42534549
Revises: 34e7375bed32
Create Date: 2024-04-29 18:33:08.641498

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e46c42534549'
down_revision = '34e7375bed32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storeitemsbyid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storeitemsbyid',
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('warehouse_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('retail_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='storeitemsbyid_item_id_fkey'),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name='storeitemsbyid_store_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name='storeitemsbyid_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='storeitemsbyid_pkey')
    )
    # ### end Alembic commands ###
